version: '3'
volumes:
  prometheus_data: {}
  grafana_data: {}
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/promtheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - ${PROMETHEUS_PORT}:9090
    restart: always
  grafana:
    image: grafana/grafana:7.1.1
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    ports:
      - ${GRAFANA_PORT}:3000
  fizzbuzz:
    build:
      context: .
    image: ngnnath/fizzbuzzserver:${FB_VERSION}
    environment:
      - SPRING_PROFILE=${SPRING_PROFILE}
      - FB_PORT=${FB_PORT}
    ports:
      - ${FB_PORT_LOCAL}:8081
    container_name: fizzbuzz_server
