{
 "title": "Grafana metrics for FizzBuzzServer",
 "description": "Metrics about Grafana",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Number Of Calls",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(fizzbuzz_requests_total)" }
   ]
  },
  {
   "title": "Request Most Called",
   "type": "bargauge",
   "description": "request called sorted by desc",
   "gridPos": { "h": 4, "w": 17, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(fizzbuzz_requests_total)",
     "legendFormat": "Request with  parameters int1 =  {{int1}},  int2 =   {{int2}},  limit =  {{limit}},  str1 =  {{str1}},  str2 =  {{str2}}"
    }
   ]
  },
  {
   "title": "5 Requests Most Called",
   "type": "bargauge",
   "description": "request called sorted by desc",
   "gridPos": { "h": 9, "w": 17, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(fizzbuzz_requests_total)"
    }
   ]
  },
  {
   "title": "Number of wrong request ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(fizzbuzz_error_parameter_total)"
    }
   ]
  }
 ]
}