scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 'localhost:9090'
  - job_name: hello-service
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'spring-boot:8081'
